### ISSUE TITLE
Temp folder cannot be created

### ISSUE THREAD

**Issue by jarecsni** [wellguimaraes/mocha-snapshots#3]
I get this exception:

1) should render:
     Error: ENOENT: no such file or directory, mkdir 'C:\dev\repos\myproject\.tmp\mocha-webpack\1515177733503\__snapshots__'
      at Error (native)
      at Object.fs.mkdirSync (fs.js:922:18)
      at module.exports (node_modules\mocha-snapshots\src\getExistingSnaps.js:9:8)
      at module.exports (node_modules\mocha-snapshots\src\matchSnapshot.js:18:28)
      at Assertion.<anonymous> (node_modules\mocha-snapshots\src\index.js:23:3)
      at Assertion.ctx.(anonymous function) [as matchSnapshot] (node_modules\chai\lib\chai\utils\addMethod.js:41:25)
      at Context.<anonymous> (.tmp\mocha-webpack\1515177733503\webpack:\src\components\Label.spec.js:8:24)
      at Test.Runnable.run (node_modules\mocha-snapshots\src\index.js:18:22)

So it seems as though mocha-webpack didnt create a folder 151517773503? I read something that mocha recently started to use an in memory fs, not sure if this has anything to do with this issue? 

Main versions:

"mocha-snapshots": "^3.0.0"
"mocha": "^4.1.0",
"mocha-webpack": "^1.0.1",

Please let me know if you need more details to be able to comment on this.

**Comment by wellguimaraes** [comment]
Sorry by the delay. Have you solved it?

**Comment by jarecsni** [comment]
No worries, and no haven't solved it. What I'm using is a sort of manual snapshot comparison instead. I'd still be interested if this could be made to work.
